version: "3.8"
# This compose file is for dev purposes

networks:
  app: {}

services:
  nginx:
    image: nginx:1.25.2-alpine
    ports:
      - "8001:80"
    volumes:
      - ./nginx-local/nginx.local-cors.conf:/etc/nginx/conf.d/default.conf

  pulsar:
    restart: always
    image: apachepulsar/pulsar:3.1.1
    ports:
      - "6650:6650"
      - "8090:8080"
    command: >
      /bin/bash -c "bin/pulsar standalone"
    networks:
      - app
    volumes:
      - ./pulsar/pulsar.conf:/pulsar/conf/standalone.conf
