# This compose file is for dev purposes

networks:
  app: {}

services:
  nginx:
    image: nginx:1.27-alpine
    ports:
      - "8001:80"
    volumes:
      - ./nginx-local/nginx.local-cors.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app

  pulsar:
    restart: always
    image: apachepulsar/pulsar:3.3.0
    ports:
      - "6650:6650"
      - "8090:8080"
    command: ["bin/pulsar", "standalone"]
    # TODO: figure out why the cpu usage is so high (on idle + healthcheck)
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
        reservations:
          cpus: '0.5'
          memory: 3G
    networks:
      - app
    healthcheck:
      test: [ "CMD-SHELL", "bin/pulsar-admin brokers healthcheck" ]
      interval: 30s
      timeout: 5s
      retries: 5
